name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 1.3.0
homepage: https://github.com/Salvatore-Giordano/CountryCodePicker

environment:
  sdk: ">=2.2.2  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/
    - packages/country_code_picker/i18n/en.json
    - packages/country_code_picker/i18n/it.json
    - packages/country_code_picker/i18n/fr.json
