name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 1.5.0
homepage: https://github.com/imtoori/CountryCodePicker

environment:
  sdk: ">=2.2.2  <3.0.0"

dependencies:
  modal_bottom_sheet: ^0.2.2
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/
    - packages/country_code_picker/i18n/en.json
    - packages/country_code_picker/i18n/it.json
    - packages/country_code_picker/i18n/fr.json
    - packages/country_code_picker/i18n/es.json
    - packages/country_code_picker/i18n/de.json
    - packages/country_code_picker/i18n/ko.json
    - packages/country_code_picker/i18n/pt.json
