name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 1.2.1
author: Salvatore-Giordano <svtgiordano@gmail.com>
homepage: https://github.com/Salvatore-Giordano/CountryCodePicker

environment:
  sdk: ">=1.19.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/
