name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 1.1.7
author: Salvatore-Giordano <svtgiordano@gmail.com>
homepage: https://github.com/Salvatore-Giordano/CountryCodePicker

environment:
  sdk: ">=1.19.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/tg.png
    - flags/me.png
    - flags/la.png
    - flags/mr.png
    - flags/ni.png
    - flags/lv.png
    - flags/om.png
    - flags/af.png
    - flags/cy.png
    - flags/bj.png
    - flags/aq.png
    - flags/cn.png
    - flags/gb-sct.png
    - flags/co.png
    - flags/cx.png
    - flags/ag.png
    - flags/ms.png
    - flags/md.png
    - flags/zm.png
    - flags/vn.png
    - flags/tf.png
    - flags/td.png
    - flags/yt.png
    - flags/lb.png
    - flags/mf.png
    - flags/lu.png
    - flags/mq.png
    - flags/cz.png
    - flags/ae.png
    - flags/cm.png
    - flags/bi.png
    - flags/ar.png
    - flags/as.png
    - flags/bh.png
    - flags/cl.png
    - flags/ad.png
    - flags/mp.png
    - flags/lt.png
    - flags/mg.png
    - flags/lc.png
    - flags/tr.png
    - flags/ua.png
    - flags/tv.png
    - flags/vi.png
    - flags/mt.png
    - flags/no.png
    - flags/mc.png
    - flags/ch.png
    - flags/bl.png
    - flags/aw.png
    - flags/bz.png
    - flags/bm.png
    - flags/ci.png
    - flags/mu.png
    - flags/us.png
    - flags/tw.png
    - flags/ye.png
    - flags/mw.png
    - flags/nl.png
    - flags/ls.png
    - flags/bo.png
    - flags/at.png
    - flags/ck.png
    - flags/by.png
    - flags/au.png
    - flags/bn.png
    - flags/ma.png
    - flags/nz.png
    - flags/lr.png
    - flags/mv.png
    - flags/tc.png
    - flags/ug.png
    - flags/tt.png
    - flags/pl.png
    - flags/rs.png
    - flags/in.png
    - flags/ge.png
    - flags/gr.png
    - flags/gs.png
    - flags/gd.png
    - flags/io.png
    - flags/hk.png
    - flags/kp.png
    - flags/gb-nir.png
    - flags/kg.png
    - flags/pm.png
    - flags/sv.png
    - flags/re.png
    - flags/sa.png
    - flags/sc.png
    - flags/st.png
    - flags/ke.png
    - flags/im.png
    - flags/kr.png
    - flags/gf.png
    - flags/dj.png
    - flags/gq.png
    - flags/gp.png
    - flags/dk.png
    - flags/gg.png
    - flags/il.png
    - flags/pn.png
    - flags/sb.png
    - flags/py.png
    - flags/ru.png
    - flags/kw.png
    - flags/do.png
    - flags/gt.png
    - flags/gb.png
    - flags/gu.png
    - flags/je.png
    - flags/hm.png
    - flags/sg.png
    - flags/pk.png
    - flags/sr.png
    - flags/se.png
    - flags/jp.png
    - flags/gw.png
    - flags/eh.png
    - flags/dz.png
    - flags/ga.png
    - flags/fr.png
    - flags/dm.png
    - flags/hn.png
    - flags/sd.png
    - flags/rw.png
    - flags/ph.png
    - flags/ss.png
    - flags/qa.png
    - flags/pe.png
    - flags/pr.png
    - flags/si.png
    - flags/ht.png
    - flags/es.png
    - flags/gl.png
    - flags/gm.png
    - flags/er.png
    - flags/fi.png
    - flags/ee.png
    - flags/kn.png
    - flags/hu.png
    - flags/iq.png
    - flags/ky.png
    - flags/sh.png
    - flags/ps.png
    - flags/pf.png
    - flags/sj.png
    - flags/id.png
    - flags/is.png
    - flags/eg.png
    - flags/fk.png
    - flags/fj.png
    - flags/gn.png
    - flags/gy.png
    - flags/ir.png
    - flags/km.png
    - flags/ie.png
    - flags/kz.png
    - flags/ro.png
    - flags/sk.png
    - flags/pg.png
    - flags/pt.png
    - flags/so.png
    - flags/sx.png
    - flags/hr.png
    - flags/ki.png
    - flags/jm.png
    - flags/eu.png
    - flags/ec.png
    - flags/et.png
    - flags/fo.png
    - flags/kh.png
    - flags/sy.png
    - flags/sn.png
    - flags/pw.png
    - flags/sl.png
    - flags/gb-eng.png
    - flags/fm.png
    - flags/gi.png
    - flags/de.png
    - flags/gh.png
    - flags/jo.png
    - flags/it.png
    - flags/pa.png
    - flags/sz.png
    - flags/sm.png
    - flags/tn.png
    - flags/ml.png
    - flags/cg.png
    - flags/ax.png
    - flags/ao.png
    - flags/bt.png
    - flags/bb.png
    - flags/cf.png
    - flags/mm.png
    - flags/li.png
    - flags/na.png
    - flags/mz.png
    - flags/to.png
    - flags/vg.png
    - flags/ve.png
    - flags/tz.png
    - flags/tm.png
    - flags/mx.png
    - flags/nc.png
    - flags/mo.png
    - flags/lk.png
    - flags/cd.png
    - flags/al.png
    - flags/bw.png
    - flags/cr.png
    - flags/bv.png
    - flags/am.png
    - flags/az.png
    - flags/ba.png
    - flags/mn.png
    - flags/nu.png
    - flags/my.png
    - flags/tl.png
    - flags/ws.png
    - flags/th.png
    - flags/xk.png
    - flags/nf.png
    - flags/ly.png
    - flags/ai.png
    - flags/br.png
    - flags/cv.png
    - flags/be.png
    - flags/ca.png
    - flags/bd.png
    - flags/cw.png
    - flags/bs.png
    - flags/ng.png
    - flags/mk.png
    - flags/np.png
    - flags/va.png
    - flags/uz.png
    - flags/um.png
    - flags/tk.png
    - flags/vc.png
    - flags/zw.png
    - flags/nr.png
    - flags/ne.png
    - flags/cu.png
    - flags/bq.png
    - flags/bf.png
    - flags/bg.png
    - flags/cc.png
    - flags/gb-wls.png
    - flags/mh.png
    - flags/za.png
    - flags/uy.png
    - flags/wf.png
    - flags/vu.png
    - flags/tj.png
    - flags/an.png
